# AlertManager Configuration v0.25.0
# Defines alert routing, grouping, and notification settings for the Data Processing Pipeline

global:
  # Global timeout for resolving alerts
  resolve_timeout: 5m

  # SMTP configuration for email notifications
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: alerts@dataprocessing.pipeline
  smtp_auth_username: ${SMTP_USERNAME}
  smtp_auth_password: ${SMTP_PASSWORD}
  smtp_require_tls: true

  # PagerDuty configuration for critical alerts
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  pagerduty_service_key: ${PAGERDUTY_KEY}

# Load notification templates
templates:
  - templates/*.tmpl

# Root routing configuration
route:
  # Default grouping rules
  group_by: ['alertname', 'cluster', 'service']
  
  # Timing parameters for initial grouping
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  
  # Default receiver if no routes match
  receiver: default-receiver

  # Severity-based routing rules
  routes:
    # Critical severity route
    - match:
        severity: critical
      receiver: pagerduty-critical
      group_wait: 0s  # Immediate notification for critical alerts
      repeat_interval: 1h  # More frequent repeats for critical issues

    # Warning severity route
    - match:
        severity: warning
      receiver: email-warnings
      group_wait: 1m
      repeat_interval: 6h  # Less frequent repeats for warnings

# Inhibition rules to prevent notification storms
inhibit_rules:
  # Suppress warning alerts if there's a critical alert for the same service
  - source_match:
      severity: critical
    target_match:
      severity: warning
    # Match these labels for inhibition to take effect
    equal: ['alertname', 'cluster', 'service']

# Notification receivers configuration
receivers:
  # Default receiver for unmatched alerts
  - name: default-receiver
    email_configs:
      - to: team@dataprocessing.pipeline
        send_resolved: true
        require_tls: true

  # PagerDuty receiver for critical alerts
  - name: pagerduty-critical
    pagerduty_configs:
      - service_key: ${PAGERDUTY_KEY}
        send_resolved: true
        severity: critical

  # Email receiver for warning alerts
  - name: email-warnings
    email_configs:
      - to: alerts@dataprocessing.pipeline
        send_resolved: true
        require_tls: true