apiVersion: v1
kind: ConfigMap
metadata:
  name: data-pipeline-config
  namespace: data-pipeline
  labels:
    app: data-pipeline
    component: config
    environment: ${ENVIRONMENT}
data:
  # API Configuration
  API_VERSION: "v1"
  DEFAULT_TIMEOUT_SECONDS: "300"
  API_RATE_LIMIT_MAX_REQUESTS: "1000"
  API_RATE_LIMIT_WINDOW_SIZE: "3600"
  
  # Logging and Monitoring
  LOG_LEVEL: "INFO"
  METRIC_COLLECTION_INTERVAL: "60"
  
  # Storage Configuration
  STORAGE_BUCKET_NAME: "${ENVIRONMENT}-data-pipeline"
  
  # Processing Parameters
  SCRAPING_CONCURRENT_REQUESTS: "16"
  OCR_BATCH_SIZE: "10"
  TASK_QUEUE_NAME: "data-pipeline-tasks"

  # Detailed Monitoring Configuration
  MONITORING_CONFIG: |
    metrics_enabled: true
    tracing_enabled: true
    logging_format: json
    log_retention_days: 90
    metric_export_interval: 60
    trace_sampling_rate: 0.1
    alert_notification_channel: cloud-monitoring
    health_check_interval: 30

  # Task Processing Configuration
  PROCESSING_CONFIG: |
    max_retries: 3
    retry_delay_seconds: 60
    batch_timeout_seconds: 600
    max_concurrent_tasks: 32
    task_priority_levels: 3
    error_threshold_percentage: 10

  # Storage Management Configuration
  STORAGE_CONFIG: |
    compression_enabled: true
    compression_level: 6
    backup_enabled: true
    backup_retention_days: 30
    lifecycle_rules_enabled: true