# Kubernetes Secret Manifest v1.24+
# Purpose: Manages sensitive configuration data for the Data Processing Pipeline
# Security: Enhanced encryption, access controls, and monitoring capabilities
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ${namespace}
  labels:
    app: data-processing-pipeline
    component: secrets
    managed-by: kustomize
  annotations:
    # Secret rotation configuration
    rotation.kubernetes.io/trigger: ${rotation_schedule}
    security.kubernetes.io/last-updated: ${timestamp}
    # Access monitoring configuration
    monitoring.kubernetes.io/access-alert: "true"
    # Additional security metadata
    security.kubernetes.io/encryption-version: "v1"
    security.kubernetes.io/access-control: "rbac"
    security.kubernetes.io/audit-level: "RequestResponse"
type: Opaque
data:
  # API Authentication Secrets
  # Purpose: Secure API access control and authentication
  API_KEY: ${base64_encoded_api_key}
  JWT_SECRET_KEY: ${base64_encoded_jwt_key}
  
  # GCP Service Account Credentials
  # Purpose: Authentication for GCP service integrations
  GCP_SERVICE_ACCOUNT_KEY: ${base64_encoded_service_account_key}
  CLOUD_STORAGE_CREDENTIALS: ${base64_encoded_storage_credentials}
  FIRESTORE_CREDENTIALS: ${base64_encoded_firestore_credentials}
  PUBSUB_CREDENTIALS: ${base64_encoded_pubsub_credentials}
  
  # External Service Authentication
  # Purpose: Integration with third-party services
  OCR_SERVICE_KEY: ${base64_encoded_ocr_key}
  ENCRYPTION_KEY: ${base64_encoded_encryption_key}
  
  # Rate Limiting Configuration
  # Purpose: API usage control and monitoring
  RATE_LIMIT_SECRET: ${base64_encoded_rate_limit_key}